[project]
name = "maptrix"
dynamic = ["version"]
description = """MapTrix - A Python implementation of Geo library for map data processing and computation, including geospatial calculations, map data manipulation, and spatial analysis tools."""
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Aman Ranjan", email = "er.amanranjan@gmail.com"}
]
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3.15",
    "Development Status :: 5 - Production/Stable",
    "Operating System :: OS Independent"
]

dependencies = [
]

[tool.setuptools]
    package-dir = {"" = "src"}

[tool.setuptools.packages.find]
    where = ["src"]

[build-system]
    requires = ["setuptools", "wheel", "cython"]
    build-backend = "setuptools.build_meta"

[dependency-groups]
    dev = [
        "cibuildwheel>=2.23.3",
        "cython>=3.2.4",
        "setuptools>=82.0.1",
    ]
    docs = [
        "myst-parser>=3.0.1",
        "sphinx>=7.4.7",
        "sphinx-autodoc-typehints>=2.3.0",
        "sphinx-rtd-theme>=3.1.0",
        "sphinxcontrib-napoleon>=0.7",
]

[tool.setuptools.dynamic]
    version = {attr = "maptrix.__version__"}

[tool.cibuildwheel]
    build = "cp310-* cp311-* cp312-* cp313-* cp314-*"
    skip = "pp*"

[tool.cibuildwheel.linux]
    manylinux-x86_64-image = "manylinux_2_28"
